### ISSUE TITLE
Some Comments and Vuestions

### ISSUE THREAD

**Issue by Kabron287** [EDrTech/bATtiny-Guard-PMG001#1]
"Battery charging is automatically managed by the IP2312 IC, which can provide up to 2A charging current to the battery. **This current is not adjustable**"

- Very bad.

What is current consumption of the module?

**Comment by EDrTech** [comment]
Well, charging current is set by resistors on the module, so it can be configured, but not easily changed once it's mounted on a PCB. I use 2C batteries with min 1000mAh at least so I set the current to my liking, since this is open source, anyone is free to set it as they please.

Current consumption is 13mA when cpu is awake, and around 0.1mA when sleeping, this is with 2x ch340c operating current calculated in, without those it would very likely be significantly smaller. Of course, when charging the battery the current can go up to 2A

**Comment by Kabron287** [comment]
When uC is in sleep state all monitoring cancelled, so coulomb counter stop working and capacity data lost?
If, so what is the practical use of this device?

**Comment by EDrTech** [comment]
Attiny1616 enters sleep mode (standby to be exact), no data is lost. The core is in standby mode but peripherals are still running (so IO state doesn't change on entering/exiting sleep). In the default firmware it wakes up once a second to take measurements, prints to serial and goes back to sleep until RTC raises the interrupt event again. 

It is planned to implement an additional I2C interface on free pins so it can send/receive data from the host uC in the near future. This is a firmware feature for which the hardware is already configured.
